[build]
	functions = "functions"

[[redirects]]
	from="/api/products"
	to="/.netlify/functions/products-read-all"
	status = 200
	method = "GET"

[[redirects]]
	from="/api/products/:id"
	to="/.netlify/functions/products-read"
	status = 200
	method = "GET"